/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface GridRangeSelection {
    }
    interface GridRowDragging {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLGridRangeSelectionElement extends Components.GridRangeSelection, HTMLStencilElement {
    }
    var HTMLGridRangeSelectionElement: {
        prototype: HTMLGridRangeSelectionElement;
        new (): HTMLGridRangeSelectionElement;
    };
    interface HTMLGridRowDraggingElement extends Components.GridRowDragging, HTMLStencilElement {
    }
    var HTMLGridRowDraggingElement: {
        prototype: HTMLGridRowDraggingElement;
        new (): HTMLGridRowDraggingElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "grid-range-selection": HTMLGridRangeSelectionElement;
        "grid-row-dragging": HTMLGridRowDraggingElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface GridRangeSelection {
    }
    interface GridRowDragging {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "grid-range-selection": GridRangeSelection;
        "grid-row-dragging": GridRowDragging;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "grid-range-selection": LocalJSX.GridRangeSelection & JSXBase.HTMLAttributes<HTMLGridRangeSelectionElement>;
            "grid-row-dragging": LocalJSX.GridRowDragging & JSXBase.HTMLAttributes<HTMLGridRowDraggingElement>;
        }
    }
}
